### ISSUE TITLE
/_node/pipeline not found 

### ISSUE THREAD

**Issue by glfp** [sloniki/logiq#1]
Hello, 

calling above api, it returns

{
path: "/_node/pipeline",
status: 404,
error: {
message: "Not Found"
}
}

Seems the api is not used at current 6.2.2 release . Any info about it ?

**Comment by sloniki** [comment]
Looks like it doesn't work for 6.x

**Comment by freddyfernando** [comment]
It should be "_node/stats/pipelines" instead of "/_node/pipeline".
Easy fix. also, the name of the pipeline has to be added in the retrieval of the data. 
I have a working fix. Let me know if you want me to contribute.

**Comment by sloniki** [comment]
@FreddyFernando that would be great
